name: augmentation
channels:
  - conda-forge
  - defaults
dependencies:
  - dask[complete]==2.9.0
  - opencv-python==4.1.2.30
  - pytest==5.3.1
  - coverage==4.5.4
  - pytest-cov==2.8.1
  - pylint==2.4.4
  - flake8==3.7.9
  - scikit-image==0.15.0
  - dotmap==1.3.8
  - jupyterlab==1.2.4
  - seaborn==0.9.0
  - requests==2.22.0
